
# https://taskfile.dev
version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  cenv:create:
    desc: _
    cmds:
      - mamba create -y -n allip python=3.10 ipython jupyter pillow opencv gst-plugins-base gst-plugins-good gstreamer


  pr:run-remote:
    cmds:
      - echo > /tmp/luki.txt
      - processing-java --sketch=$(realpath .) --output=/tmp/processing/test --force --run {{.CLI_ARGS}} | tee /tmp/luki.txt
    env:
      DISPLAY: ":0"
    desc: _ 

  voices:list-devices:
    cmds:
      - aplay -l
    desc: _

  voices:play:with-vlc:
    cmds:
      - |
        cvlc \
          --aout alsa \
          --alsa-audio-device hw:3,0 \
          --volume 200 \
          --loop \
          $(realpath ~/data/altar.voices/MOFAIM.KFAR-BLUM.JUNE-01-2024.13PM.wav)
    desc: _

  voices:play:with-ffplay:
    cmds:
      - |
        ffplay \
          -nodisp \
          -autoexit \
          -loop 0 \
          -volume 100 \
          $(realpath ~/data/altar.voices/MOFAIM.KFAR-BLUM.JUNE-01-2024.13PM.wav)
    env:
      SDL_AUDIODRIVER: "alsa"
      AUDIODEV: "hw:3,0"
    desc: _
  
  list-displays:
    cmds:
      - |
        DISPLAY=:0 xrandr --listmonitors
    desc: _
    silent: yes

  list-network-devices:
    cmds:
      - sudo arp-scan --localnet --resolve
    desc: _      