
# https://taskfile.dev
version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  cenv:create:
    desc: _
    cmds:
      - mamba create -y -n allip python=3.10 ipython jupyter pillow opencv gst-plugins-base gst-plugins-good gstreamer

  images:play:with-processing:
    cmds:
      - bash -c "nohup processing-java --sketch=$(realpath .) --output=/tmp/processing/test --force --run {{.CLI_ARGS}} | tee images__play__with-processing.log &"
      - sudo logrotate -f logrotate-images.conf
    env:
      DISPLAY: ":0"
    desc: _ 

  images:kill:
    cmds:
      - ./kill-processing.sh
    desc: __

  images:run:remotely:
    cmds:
      - |
        ssh altar@altar.local 'task -d /home/altar/repos/allip images:play:with-processing'
    desc: _

  images:kill:remotely:
    cmds:
      - |
        ssh altar@altar.local 'task -d /home/altar/repos/allip images:kill'
    desc: _

  voices:run:remotely:
    cmds:
      - |
        ssh altar@altar-voices.local 'task -d /home/altar/repos/allip voices:play:with-mpv'
    desc: _

  voices:kill:remotely:
    cmds:
      - |
        ssh altar@altar.local 'task -d /home/altar/repos/allip voices:kill'
    desc: _

  voices:list-devices:
    cmds:
      - aplay -l
    desc: _

  voices:play:with-vlc:
    cmds:
      - |
        cvlc \
          --aout alsa \
          --alsa-audio-device hw:2,0 \
          --volume 200 \
          --loop \
          $(realpath ~/data/altar.voices/MOFAIM.KFAR-BLUM.JUNE-01-2024.13PM.wav)
    desc: _

  voices:play:with-mpv:
    vars:
      START: '{{default "300" .START}}'
      FILE: '{{default "/home/altar/pawns.court/nazeret.audio/STE-045__Nazeret__2.wav" .FILE}}'
      VOLUME: '{{default "240" .VOLUME}}'
    cmds:
      - bash -c "nohup mpv --loop=inf --volume={{.VOLUME}} --start={{.START}} --audio-device=alsa/plughw:CARD=DAC,DEV=0 $(realpath {{.FILE}}) | tee voices__play__with-mvp.log &"
      - sudo logrotate -f logrotate-voices.conf
    desc: |
      Headphones = alsa/plughw:CARD=Headphones,DEV=0
      DAC = alsa/plughw:CARD=DAC,DEV=0

  voices:kill:
    cmds:
      - pkill mpv
    desc: __

  voices:play:with-ffplay:
    cmds:
      - |
        ffplay \
          -nodisp \
          -autoexit \
          -loop 0 \
          -volume 100 \
          $(realpath ~/data/altar.voices/MOFAIM.KFAR-BLUM.JUNE-01-2024.13PM.wav)
    env:
      SDL_AUDIODRIVER: "alsa"
      AUDIODEV: "hw:3,0"
    desc: _
  
  list-displays:
    cmds:
      - |
        DISPLAY=:0 xrandr --listmonitors
    desc: _
    silent: yes

  list-network-devices:
    cmds:
      - sudo arp-scan --localnet --resolve
    desc: _

  video:loop:cvlc:
    desc: |
      # "--start-time=26 --stop-time=32"
      # to control vlc, in a sperate terminal run:
        >$ nc localhost 4212
        then you can:
         .. pause
         .. play
         .. stop
         .. quit
    env:
      DISPLAY: ":0"
    cmds:
      - |
        cvlc \
          --extraintf rc \
          --rc-host localhost:4212 \
          --loop \
          --fullscreen \
          --no-video-title-show /home/altar/pawns.court/altar.aleph/exports/D01.HAND.w.LAMP__HAND.and.WHITE.mp4__FULL_FRAME.mp4


  pr:run-remote:deprecated:
    cmds:
      - echo > /tmp/luki.txt
      - processing-java --sketch=$(realpath .) --output=/tmp/processing/test --force --run {{.CLI_ARGS}} | tee /tmp/luki.txt
    env:
      DISPLAY: ":0"
    desc: _ 
